name: Prepare Buildpack Release
description: "Prepares a buildpack release by bumping the fixed version and updating changelogs"

inputs:
  bump:
    required: true

outputs:
  from_version:
    value: ${{ steps.prepare.outputs.from_version }}
  to_version:
    value: ${{ steps.prepare.outputs.to_version }}
  unreleased_changes:
    value: ${{ steps.prepare.outputs.unreleased_changes }}

runs:
  using: "composite"
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - id: install-rust-toolchain
      name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
    - name: Rust cache
      uses: Swatinem/rust-cache@v2
    - id: prepare
      name: Prepare Release
      run: |
        cd ${{ github.action_path }}
        cargo run --bin prepare_release -- --bump ${{ inputs.bump }} ${{ github.workspace }}
      shell: bash
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        title: Prepare release v${{ steps.prepare.outputs.to_version }}
        commit-message: Prepare release v${{ steps.prepare.outputs.to_version }}
        branch: release/v${{ steps.prepare.outputs.to_version }}
        body: ${{ steps.prepare.outputs.unreleased_changes }}
        labels: "automation"