name: Save buildpack release output
description: Saves various artifacts used in the buildpack release phases

inputs:
  buildpack_id:
    required: true
    description: The buildpack id to cache artifacts for
  buildpack_version:
    required: true
    description: The buildpack version
  docker_repository:
    required: true
    description: The repository name to be used in Docker publishing
  changes:
    required: true
    description: This content will be used in PRs and GitHub Releases created
  cnb_file:
    required: true
    description: The path to the package .cnb buildpack file
  docker_image:
    required: true
    description: The path to the compressed docker image

runs:
  using: composite
  steps:
    - name: Save Buildpack Variables
      shell: bash
      run: |
        cat << "EOF" > ./${{ inputs.buildpack_id }}.metadata
        buildpack_version=${{ inputs.buildpack_version }}
        docker_repository=${{ inputs.docker_repository }}
        EOF
        cat ./${{ inputs.buildpack_id }}.metadata
    - name: Save Changelog
      shell: bash
      run: |
        cat << "EOF" > ./${{ inputs.buildpack_id }}.changes
        ${{ steps.generate-changelog.outputs.changelog }}
        EOF
        cat ./${{ inputs.buildpack_id }}.changes
    - name: Move CNB file
      shell: bash
      run: |
        if [ "${{ inputs.cnb_file }}" != "${{ inputs.buildpack_id }}.cnb" ]; then 
          mv ${{ inputs.cnb_file }} ${{ inputs.buildpack_id }}.cnb
        fi
    - name: Move Docker image
      shell: bash
      if: ${{ inputs.docker_image }} != ${{ inputs.buildpack_id }}.tar.zst
      run: |
        if [ "${{ inputs.docker_image }}" != "${{ inputs.buildpack_id }}.tar.zst" ]; then 
          mv ${{ inputs.docker_image }} ${{ inputs.buildpack_id }}.tar.zst
        fi
    - uses: actions/cache/save@v3
      with:
        key: ${{ github.run_id }}-${{ inputs.buildpack_id }}
        path: |
          ${{ inputs.buildpack_id }}.cnb
          ${{ inputs.buildpack_id }}.tar.zst
          ${{ inputs.buildpack_id }}.metadata
          ${{ inputs.buildpack_id }}.changes