name: Save buildpack release output
description: Saves various artifacts used in the buildpack release phases

inputs:
  buildpack_id:
    required: true
    description: The buildpack id to cache artifacts for

outputs:
  buildpack_version:
    description: The buildpack version
    value: ${{ steps.metadata.outputs.buildpack_version }}
  docker_repository:
    description: The repository name to be used in Docker publishing
    value: ${{ steps.metadata.outputs.docker_repository }}
  changes_file:
    description: This content will be used in PRs and GitHub Releases created
    value: ${{ inputs.buildpack_id }}.changes
  cnb_file:
    description: The path to the package .cnb buildpack file
    value: ${{ inputs.buildpack_id }}.cnb
  docker_image:
    description: The path to the compressed docker image
    value: ${{ inputs.buildpack_id }}.tar.zst

runs:
  using: composite
  steps:
    - name: Restore cached assets
      uses: actions/cache/restore@v3
      with:
        key: ${{ github.run_id }}-${{ inputs.buildpack_id }}
        path: |
          ${{ inputs.buildpack_id }}.cnb
          ${{ inputs.buildpack_id }}.tar.zst
          ${{ inputs.buildpack_id }}.metadata
          ${{ inputs.buildpack_id }}.changes
    - name: Restore buildpack metadata
      id: metadata
      shell: bash
      run: cat ${{ inputs.buildpack_id }}.metadata >> $GITHUB_OUTPUT


