name: Update Builder
description: "Prepares a buildpack release by bumping the fixed version and updating changelogs"

inputs:
  buildpack-id:
    description: The id of the buildpack
    required: true
  buildpack-version:
    description: The version of the buildpack
    required: true
  buildpack-uri:
    description: The URI of the published buildpack
    required: true
  builders:
    description: A comma-separated list of builders to update
    required: true

runs:
  using: node16
  main: index.js