name: Prepare Buildpack Release

on:
  workflow_call:
    inputs:
      bump:
        description: "Bump"
        required: true
        type: string
    secrets:
      app_id:
        description: "GitHub application ID"
        required: true
      app_private_key:
        description: "Private key of the GitHub application"
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare-release:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare
        id: prepare_release
        uses: colincasey/languages-github-action/.github/actions/prepare-release@main
        with:
          bump: ${{ inputs.bump }}
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ inputs.app_id }}
          private_key: ${{ inputs.app_private_key }}
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate-token.outputs.token }}
          title: Prepare release v${{ steps.prepare_release.outputs.to_version }}
          commit-message: Prepare release v${{ steps.prepare_release.outputs.to_version }}
          branch: release/v${{ steps.prepare_release.outputs.to_version }}
          body: ${{ steps.prepare_release.outputs.changelog_summary }}
          labels: "automation"
      - name: Configure PR
        if: steps.pr.outputs.pull-request-operation == 'created'
        run: gh pr merge --auto --squash "${{ steps.pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}